### ISSUE TITLE
new-linode_harden can't finish unless user running the playbook is last in user list

### ISSUE THREAD

**Issue by Zarex** [maximum-ethics/linode-caddy#2]
This [handler](https://github.com/maximum-ethics/linode-caddy/blob/a7cad3a2824f689050a04bf21e98103c8be745f3/roles/new-linode_harden/handlers/main.yml#L6) currently requires the user's entry to be last in the list of users! Otherwise it can't finish because the user hasn't updated their password yet. There must be some better way to do this that doesn't require us to manually rearrange the user list depending on who is running the playbook.

**Comment by Zarex** [comment]
Suggested fix might be to create a user that is used in the setup roles and have it be always at the end of the list of users.  This user could be deleted after the setup is fully finished.

**Comment by skyfaller** [comment]
I have an idea: if we prompt the person running the playbook for their password, then they don't need to change their password because they won't be using a default password. If they don't need to update their password, they can be anywhere in the list of users, they'll still be able to finish running the playbook.

**Comment by skyfaller** [comment]
We need to:

- Find in the array of users the username that matches the username entered at prompt
- Change that user's password to the password entered at prompt
- Set a conditional for the handler that forces you to change your password at first login, so that the user running the playbook doesn't have to change their password

Some possibly useful links:

- https://ttl255.com/jinja2-tutorial-part-2-loops-and-conditionals/
- https://stackoverflow.com/questions/71037638/replace-items-in-a-list-ansible-playbook

**Comment by skyfaller** [comment]
Actually, new possible approach:
- take existing list of users, delete prompt user from it
- create prompt user on OS separately
- run the handler to reset passwords as usual for everyone else (prompt user won't be included in `new_accounts.results` and therefore won't have its password force changed)

**Comment by Zarex** [comment]
Jinja2 Control Flow Documentation: https://ttl255.com/jinja2-tutorial-part-2-loops-and-conditionals/
Example: https://stackoverflow.com/questions/71037638/replace-items-in-a-list-ansible-playbook
We were trying to figure out how we should use jinja2 conditionals within our play and used the above link as an example to dissect what they did and we figured it out.

"vars:" under the set_fact module will register variables, they can be used in the rest of module

loop: "{{ dict_ns_cpu|dict2items }}"
this breaks down the dictionary into items that can be iterated and accessed with item.key and item.value for each iteration of the loop

the _list var uses jinja2 for loops and if statements to create a yaml list from the list of numbers in dict_ns_cpu.  If it has an m it divides by 1000, otherwise it multiplies by 1000, and each item of the list becomes an item in the yaml list

result compiles all of this together, creates a new dictionary if it didn't already exist, and then combines that with a dictionary created from item.key and a list compiled from the yaml list in the vars section.

**Comment by Zarex** [comment]
Where we left off: We figured out how to separate the lists, we set the password for the self_excluded_user, and were thwarted by the next step of starting the linode-harden playbook.  It was giving us invalid password after running the first two steps which included our altered work, so we guessed that the password wasn't the same anymore because whatever method of sudoing was being used before probably assumed the default password because that's what **_everybody's_** password was.  We had a hell of a time trying to get Ansible to remember the password when we were changing hosts, and eventually were trying to set the password with the connection property ansible_become_password.  That was brickwalling us saying invalid password and we ran it with a lot of v's and seeing "User = None" made me think we should set ansible_become_user as well even though we didn't need it before.  At that point the error message changed and it seemed like the command being run just wasn't using sudo at all for some reason.  We decided to pick up next time from here.

Question for next time: How was it working before?  Did it have to do with any specific local machine configuration?

https://docs.ansible.com/ansible/latest/user_guide/become.html#become-connection-variables

**Comment by skyfaller** [comment]
I found where the incorrect password was coming from:

https://github.com/maximum-ethics/linode-caddy/blob/master/roles/new-linode_harden/vars/main.yml

We were storing the default password in a variable in the vars directory.

Removing that should allow whatever else we were trying to work, I think our other efforts were getting clobbered. Not sure what the precedence is, but Murphy's law suggests it's whatever was least convenient for us.

**Comment by skyfaller** [comment]
I know this works on my Mac now. If it doesn't work on other machines, we can reopen this ticket or start a new issue.

Primarily fixed in this commit: https://github.com/maximum-ethics/linode-caddy/commit/ac478e2f4eb9b56330969370946697fb41059893
