### ISSUE TITLE
Playbook runs on a brand new Linux desktop installation

### ISSUE THREAD

**Issue by Zarex** [maximum-ethics/linode-caddy#3]
Create a new linux distribution, boot it up and document the steps required to get existing playbooks running

Acceptance Criteria: Document process of equipping a new linode instance to be able to run ansible playbooks

**Comment by Zarex** [comment]
using a linode instance as our fresh linux install
Documenting in readme

Acceptance Criteria: Document process of equipping a new linode instance to be able to run ansible playbooks

**Comment by skyfaller** [comment]
Fixed in https://github.com/maximum-ethics/linode-caddy/commit/d26d8f7c493721c4c769e286cfe49bc8e7a3d4f3, documentation updated.
