### ISSUE TITLE
Manual step for building caddy from AUR

### ISSUE THREAD

**Issue by Zarex** [maximum-ethics/linode-caddy#6]
https://github.com/maximum-ethics/linode-caddy/blob/0cc58e330bc3363d605ba948822b373b0813f79d/roles/sunrise/tasks/main.yml#L69-L82

This is another manual step introduced to allow us to build caddy from the AUR

**Comment by skyfaller** [comment]
We fixed the keyserver issue by [switching to a different AUR package](https://github.com/maximum-ethics/linode-caddy/commit/b7e51ef6b75fe90e9bc1c8e4fb9db805b4b07daf).

Now the issue should be more permanently fixed by abandoning reliance on AUR altogether.
